# lua2c.cmake - Convert Lua source files to C string literals in a header.
#
# Usage:
#   cmake -DLUA_FILE_1=file1.lua -DVAR_NAME_1=var1
#         -DLUA_FILE_2=file2.lua -DVAR_NAME_2=var2
#         -DOUTPUT_FILE=output.h
#         -P lua2c.cmake
#
# Generates a header with:
#   static const char var1[] = "...escaped content...";
#   static const char var2[] = "...escaped content...";

if(NOT DEFINED OUTPUT_FILE)
    message(FATAL_ERROR "lua2c.cmake requires OUTPUT_FILE")
endif()

# Collect all LUA_FILE_N / VAR_NAME_N pairs
set(_files "")
set(_vars "")
set(_i 1)
while(DEFINED LUA_FILE_${_i})
    list(APPEND _files "${LUA_FILE_${_i}}")
    list(APPEND _vars "${VAR_NAME_${_i}}")
    math(EXPR _i "${_i} + 1")
endwhile()

list(LENGTH _files _nfiles)
if(_nfiles EQUAL 0)
    message(FATAL_ERROR "lua2c.cmake: no LUA_FILE_N variables provided")
endif()

set(_output "/* Auto-generated by lua2c.cmake -- do not edit. */\n")
string(APPEND _output "#ifndef FFI_LUA_EMBEDDED_H\n")
string(APPEND _output "#define FFI_LUA_EMBEDDED_H\n\n")

math(EXPR _last "${_nfiles} - 1")
foreach(_i RANGE 0 ${_last})
    list(GET _files ${_i} _file)
    list(GET _vars ${_i} _var)

    file(READ "${_file}" _content)

    # Escape backslashes first, then double quotes, then newlines
    string(REPLACE "\\" "\\\\" _content "${_content}")
    string(REPLACE "\"" "\\\"" _content "${_content}")
    string(REPLACE "\n" "\\n\"\n\"" _content "${_content}")

    string(APPEND _output "static const char ${_var}[] =\n\"${_content}\";\n\n")
endforeach()

string(APPEND _output "#endif /* FFI_LUA_EMBEDDED_H */\n")

file(WRITE "${OUTPUT_FILE}" "${_output}")
